// Generated by py2rust -- review all AMBIGUOUS/UNSUPPORTED markers.
// Source: sample.py

// (Python import 'requests' -- add the equivalent Rust crate manually)

fn clamp(value: i64, lo: i64, hi: i64) -> i64 {
    // keep value within [lo, hi]
    if (value < lo) {
        return lo;
    }
    if (value > hi) {
        return hi;
    }
    return value;
}

fn sum_up_to(n: i64) -> i64 {
    let mut total: i64 = 0;
    for i in 0..n {
        total = (total + i);
    }
    return total;
}

// AMBIGUOUS[class-shape]: 'Counter' was translated as a plain struct; reconsider a trait object if it's used polymorphically elsewhere in the project.
pub struct Counter {
    pub value: i64,
    pub history: Vec<i64>,
}

impl Counter {
    pub fn new(value: i64, history: Vec<i64>) -> Self {
        Self {
            value,
            history,
        }
    }

    fn increment(&mut self, amount: i64) {
        self.value = (self.value + amount);
        // keep a record of every value we've held
        // AMBIGUOUS[iteration-style]: Iterating by shared reference is the safe default; switch to into_iter() if the loop body needs to own each element.
        for h in self.history.iter() {
            println!("{}", h);
        }
    }

    fn report(&self) -> i64 {
        if (self.value > 100) {
            // AMBIGUOUS[error-handling]: Python 'raise ...' was translated as a panic; consider a Result-based rewrite for recoverable errors.
            panic!("{}", "counter overflowed".to_string());
        }
        return self.value;
    }
}

fn fetch_data(url: String) -> String {
    // SUGGESTED CRATE: consider `reqwest` (blocking client) (add `reqwest = { version = "*", features = ["blocking"] }`)
    let response: String = requests.get(url);
    return response;
}
