// Generated by code-convert-helper -- review all AMBIGUOUS/TYPE HOLE/OWNERSHIP/UNSUPPORTED markers.
// Source: sample.py

// (Python import 'requests' -- add the equivalent Rust crate manually)

// OWNERSHIP (inferred 'owner'): 'i64' is a Copy primitive; pass-by-value is idiomatic
// OWNERSHIP (inferred 'owner'): 'i64' is a Copy primitive; pass-by-value is idiomatic
// OWNERSHIP (inferred 'owner'): 'i64' is a Copy primitive; pass-by-value is idiomatic
// OWNERSHIP (inferred 'move'): return value is constructed or computed in the function body
fn clamp(value: i64, lo: i64, hi: i64) -> i64 {
    // keep value within [lo, hi]
    if value < lo {
        return lo;
    }
    if value > hi {
        return hi;
    }
    value
}

// OWNERSHIP (inferred 'owner'): 'i64' is a Copy primitive; pass-by-value is idiomatic
// OWNERSHIP (inferred 'move'): return value is constructed or computed in the function body
fn sum_up_to(n: i64) -> i64 {
    // OWNERSHIP (inferred 'owner'): 'total = ...' binds a new owned local by default
    let mut total: i64 = 0;
    for i in 0..n {
        total += i;
    }
    total
}

// OWNERSHIP CONFLICT: directive says 'refer' but usage-based inference would have chosen 'move' (returned directly from the function)
// OWNERSHIP (inferred 'refer'): returns parameter 'name' unchanged, itself resolved as 'refer'
fn greet(name: &String) -> &String {
    // 'name' is only read here, so a borrow avoids an unnecessary clone;
    // the return type echoes that same reference automatically.
    name
}

// OWNERSHIP CONFLICT: directive says 'move' but usage-based inference would have chosen 'refer' ('name' is only read or passed along; never stored or returned)
// OWNERSHIP CONFLICT: directive says 'owner' but usage-based inference would have chosen 'move' (return value is constructed or computed in the function body)
fn build_greeting(name: String) -> String {
    // ownership transfers into 'greeting' below, so the parameter itself
    // is consumed rather than borrowed.
    // TYPE HOLE hole_0002: no evidence gathered yet
    let greeting: TypeHole_hole_0002 = name;
    greeting
}

// AMBIGUOUS[class-shape]: 'Counter' was translated as a plain struct; reconsider a trait object if it's used polymorphically elsewhere in the project.
pub struct Counter {
    pub value: i64,
    pub history: Vec<i64>,
}

impl Counter {
    pub fn new(value: i64, history: Vec<i64>) -> Self {
        Self {
            value,
            history,
        }
    }

    // OWNERSHIP (inferred 'owner'): 'i64' is a Copy primitive; pass-by-value is idiomatic
    // OWNERSHIP (inferred 'move'): function has no return value
    fn increment(&mut self, amount: i64) {
        self.value += amount;
        // keep a record of every value we've held
        // AMBIGUOUS[iteration-style]: Iterating by shared reference is the safe default; switch to into_iter() if the loop body needs to own each element.
        for h in &self.history {
            println!("{h}");
        }
    }

    // OWNERSHIP (inferred 'move'): return value is constructed or computed in the function body
    fn report(&self) -> i64 {
        if self.value > 100 {
            // AMBIGUOUS[error-handling]: Python 'raise ...' was translated as a panic; consider a Result-based rewrite for recoverable errors.
            panic!("counter overflowed");
        }
        self.value
    }
}

// OWNERSHIP (inferred 'refer'): 'url' is only read or passed along; never stored or returned
// TYPE HOLE hole_0003: no type hint; not yet inferred from call sites
// OWNERSHIP (inferred 'move'): return value is constructed or computed in the function body
// TYPE HOLE hole_0004: returns 'response', type not resolved
fn fetch_data(url: &TypeHole_hole_0003) -> TypeHole_hole_0004 {
    // SUGGESTED CRATE: consider `reqwest` (blocking client) (add `reqwest = { version = "*", features = ["blocking"] }`)
    // OWNERSHIP (inferred 'owner'): 'response = ...' binds a new owned local by default
    // TYPE HOLE hole_0005: no evidence gathered yet
    let response: TypeHole_hole_0005 = requests.get(url);
    response
}
